apiVersion: v1
kind: Service
metadata:
  name: secure-learn-app
  labels:
    app.kubernetes.io/name: secure-learn
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secure-learn
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 3000
      targetPort: http
